### ISSUE TITLE
some other graph level classification papers

### ISSUE THREAD

**Issue by David-AJ** [benedekrozemberczki/awesome-graph-embedding#10]
Hi, those are some other graph level classification papers for your information
Graph Kernel:
"A Graph Kernel Based on the Jensen-Shannon Representation Alignment" IJCAI 2015
Lu Bai, Zhihong Zhang, Chaoyan Wang, Xiao Bai, Edwin R. Hancock
paper: http://ijcai.org/Proceedings/15/Papers/468.pdf
code: https://github.com/baiuoy/Matlab-code-JS-alignment-kernel-IJCAI-2015

“An Aligned Subtree Kernel for Weighted Graphs” ICML 2015
Lu Bai, Luca Rossi, Zhihong Zhang, Edwin R. Hancock
paper: http://proceedings.mlr.press/v37/bai15.pdf
code will be released soon

Deep Learning:
"Learning Aligned-Spatial Graph Convolutional Networks for Graph Classification" ECML-PKDD 2019
Lu Bai, Yuhang Jiao, Lixin Cui, Edwin R. Hancock
paper: https://arxiv.org/abs/1904.04238
code: https://github.com/baiuoy/ASGCN_ECML-PKDD2019 (will be released soon)

**Comment by benedekrozemberczki** [comment]
Added.
