### ISSUE TITLE
Graph classification based on topological features

### ISSUE THREAD

**Issue by Pseudomanifold** [benedekrozemberczki/awesome-graph-embedding#11]
Hi there,

please add our paper “A Persistent Weisfeiler–Lehman Procedure for Graph Classification” as well to this repository:

Paper: http://proceedings.mlr.press/v97/rieck19a/rieck19a.pdf
Code: https://github.com/BorgwardtLab/P-WL

Best,
  Bastian

**Comment by benedekrozemberczki** [comment]
Added :)

**Comment by Pseudomanifold** [comment]
Fantastic, thank you so much! :)
