### ISSUE TITLE
Graph classification method from ICDM '19

### ISSUE THREAD

**Issue by markheimann** [benedekrozemberczki/awesome-graph-embedding#13]
Hi, thanks for maintaining such a comprehensive list of methods for graph-level machine learning.  I am an author of the ICDM 2019 paper "Distribution of Node Embeddings as Multiresolution Features for Graphs" and was wondering if it could be included on this list?  
Overview: Derives a randomized feature map for a graph based on the distribution of its node embeddings in vector space.  As the proposed technique is an explicit feature map, it probably fits in the section on "spectral and statistical fingerprints", but its theoretical underpinnings come from the graph kernel literature and so it might fit in that section instead.  Won best student paper at ICDM 2019.  
Paper: [https://ieeexplore.ieee.org/document/8970922]
Code: [https://github.com/GemsLab/RGM]

**Comment by benedekrozemberczki** [comment]
Hi there Mark,

Sorry, for the late reply. I will add it, I have actually read this paper. 

Benedek

**Comment by benedekrozemberczki** [comment]
It will go under graph kernels if that is okay with you. Please take a look:

https://github.com/benedekrozemberczki/awesome-graph-classification/blob/master/kernels.md

**Comment by markheimann** [comment]
Hi Benedek,

I think that’s a good place for it, since it is a very “kernel-y” work.  Thanks for that, and for all the resources you provide the graph mining community! 


Best,
Mark
