### ISSUE TITLE
KDD2020 Paper

### ISSUE THREAD

**Issue by tlancian** [benedekrozemberczki/awesome-graph-embedding#16]
Hi,

in our KDD2020 work we solve a graph classification problem with nice results!

Paper: https://dl.acm.org/doi/10.1145/3394486.3403383
Code: https://github.com/tlancian/contrast-subgraph

Would you add it to the repo?

Thank you,
Tommaso

**Comment by benedekrozemberczki** [comment]
Hi Tommaso,

Added the paper. Nice work!

Benedek
