### ISSUE TITLE
A Simple Yet Effective Baseline for Non-Attribute Graph Classification

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [benedekrozemberczki/awesome-graph-embedding#4]
Hi,

Thank you for your paper list. I am the author of the paper A Simple Yet Effective Baseline for Non-Attribute Graph Classification. It has been accepted by ICLR 2019 graph representation learning workshop (https://rlgm.github.io/). Would you like to update the record? Thanks!

Best,
Chen

**Comment by benedekrozemberczki** [comment]
Yes.
