### ISSUE TITLE
Please add KDD 2019 paper, data, code

### ISSUE THREAD

**Issue by srijankr** [benedekrozemberczki/awesome-graph-embedding#5]
Hi! 

Thank you for this awesome repository! 

Could you please add the following paper, code, and data link to the repository: 
Paper: Predicting Dynamic Embedding Trajectory in Temporal Interaction Networks
Authors: Srijan Kumar, Xikun Zhang, Jure Leskovec
Venue: ACM SIGKDD 2019 (Proceedings of the 25th ACM SIGKDD international conference on Knowledge discovery and data mining)
Project page: http://snap.stanford.edu/jodie/
Code: https://github.com/srijankr/jodie/
All datasets: http://snap.stanford.edu/jodie/

Many thanks,
Srijan

**Comment by benedekrozemberczki** [comment]
Hi there, Is this a node level embedding paper?

**Comment by srijankr** [comment]
Yes!

**Comment by benedekrozemberczki** [comment]
This repository covers graph level problems (e.g. DiffPool, Graph2Vec
etc.). However, there are another repos (one of them with way more stars)
maintained by some lovely people that work at the node level:

https://github.com/chihming/awesome-network-embedding
https://github.com/naganandy/graph-based-deep-learning-literature
