### ISSUE TITLE
Missing SAGPool

### ISSUE THREAD

**Issue by choltz95** [benedekrozemberczki/awesome-graph-embedding#6]
Attention-based pooling operator without having to learn n^2 cluster-assignment matrix as in DiffPool.
paper: https://arxiv.org/abs/1904.08082
code: https://github.com/inyeoplee77/SAGPool

**Comment by benedekrozemberczki** [comment]
Thank You! I will add it.

**Comment by benedekrozemberczki** [comment]
Added.
