### ISSUE TITLE
Another graph paper

### ISSUE THREAD

**Issue by roeiherz** [benedekrozemberczki/awesome-graph-embedding#8]
You can also add to the list "Mapping Images to Scene Graphs with Permutation-Invariant Structured Prediction" from NeurIPS18.

It's a novel graph architecture for mapping images to scene graphs using a permutation invariant property, which achieves a new state-of-the-art results on Visual Genome dataset.

paper: https://arxiv.org/abs/1802.05451
code: https://github.com/shikorab/SceneGraph

**Comment by benedekrozemberczki** [comment]
I will add it today. If I forgot please drop me a line.

**Comment by benedekrozemberczki** [comment]
Added :)

**Comment by roeiherz** [comment]
Thanks :)
