### ISSUE TITLE
Updates of the library py-graph

### ISSUE THREAD

**Issue by jajupmochi** [benedekrozemberczki/awesome-graph-embedding#9]
Hi, I am the author of the library [py-graph](https://github.com/jajupmochi/py-graph). Thanks a lot for including our library! Just to inform you that we updated our library and now there are implementations for 8 graph kernels. We also upload our library to [PyPI](https://pypi.org/project/py-graphs/). Thanks!

**Comment by benedekrozemberczki** [comment]
I will go over and add each of the papers. Thank You for pointing out!

**Comment by benedekrozemberczki** [comment]
Added.
